### ISSUE TITLE
Sensor Plotter drop down not auto populating

### ISSUE THREAD

**Issue by Zenaking14** [udellc/Loom4Max#4]
Currently, the option boxes for the sensor plotters must both be selected before the data shows on the plotter. The second drop down shows the first available option under the umbrella of the first one selected but it does not automatically display the data for that combination.

Potential fix: send a slightly delayed message to refresh all plotters after an option has been selected.
![image_2022-11-17_024803193](https://user-images.githubusercontent.com/62921614/202426556-271ffe29-9fb9-4459-8244-bf76704d360e.png)

**Comment by udellc** [comment]
I did a soft fix in the sensor plotter maxpat file. When a new main menu item is selected, delay 20ms and then send a bang to the submenu, auto-sending the first item in the submenu to retrieve and plot the correct data. This is a hack-fix and needs to be solved for real though. Because when a new first menu item is chosen, the bondo object automatically sends an erroneous concatenated reference with the latest main menu, and the submenu item of the previously selected main device. So there is an error message saying "no such sensor exists".  
<img width="1135" alt="Screen Shot 2022-12-06 at 2 49 29 PM" src="https://user-images.githubusercontent.com/22646767/206041755-6a8faf4e-09d6-4bf1-ad38-532661815db6.png">
